version: '3.3'

services:
  todo-api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/var/www/html'
    ports:
      - "5000:5000"
  
  mongo:
    image: mongo:4.2.6
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: docker
 
  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: docker